CREATE SCHEMA IF NOT EXISTS todolist DEFAULT CHARACTER SET utf8;
USE todolist;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) UNIQUE NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT NOT NULL AUTO_INCREMENT,
  userId BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (userId) REFERENCES users(id)
)

ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS linkedTasks (
  id BIGINT NOT NULL AUTO_INCREMENT,
  taskId BIGINT NOT NULL,
  linkedTaskId BIGINT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (taskId) REFERENCES tasks(id),
  FOREIGN KEY (linkedTaskId) REFERENCES tasks(id)
)

ENGINE = InnoDB;

INSERT INTO users (name) VALUES ("admin");
